Main:
  Hello: world
Model:
  output_classes: ['ORG', 'PER', 'LOC', 'MISC']
Utils:
  special_tokens: {'pad_idx': 0, 'sos_idx': 1, 'eos_idx': 2, 'unk_idx': 3}

Train:

Sampler:

Tester:
  batch_size: 2
  max_sequence_length: 10
  epochs: 5
  # Iterations are particularly for SVAE and Discriminator components
  iterations: 5
  model_type: task_learner
