Main:

Model:
  output_classes: ['ORG', 'PER', 'LOC', 'MISC']
  Discriminator:
  # currently not using
    z_dim: 8
Utils:
  special_tokens: {'pad_idx': 0, 'sos_idx': 1, 'eos_idx': 2, 'unk_idx': 3}
Train:
  epochs: 2
  svae_steps: 2
  discriminator_steps: 2
  learning_rates:
    task_learner: 0.01
    svae: 0.001
    discriminator: 0.001
Sampler:

Tester:
  batch_size: 2
  max_sequence_length: 10
  epochs: 5
  # Iterations are particularly for SVAE and Discriminator components
  iterations: 5
  # task_learner, discriminator, svae
  model_type: svae
