Main:
Model:
  output_classes: ['ORG', 'PER', 'LOC', 'MISC']
  Discriminator:
  # currently not using
    z_dim: 8
Utils:
  special_tokens: {'pad_idx': 0, 'sos_idx': 1, 'eos_idx': 2, 'unk_idx': 3}
Train:

Sampler:

Tester:
  batch_size: 2
  max_sequence_length: 10
  epochs: 5
  # Iterations are particularly for SVAE and Discriminator components
  iterations: 5
  # task_learner, discriminator, SVAE
  model_type: discriminator
